version: '3.3'
services:
  jupyter:
    container_name: jupyter_notebook
    build:
      context: .
      dockerfile: Dockerfile-alternate
    ports:
    - 8888:8888/tcp
    volumes:
    - .:/home/jovyan:rw
