#!/usr/bin/env bash

## How to get files into binder.
# https://github.com/binder-examples/getting-data
wget -q -O bikes-2016.csv "https://data.stadt-zuerich.ch/dataset/verkehrszaehlungen_werte_fussgaenger_velo/resource/ed354dde-c0f9-43b3-b05b-08c5f4c3f65a/download/2016verkehrszaehlungenwertefussgaengervelo.csv"

# minio binary
wget https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio
